### ISSUE TITLE
Response always returns status code of 200

### ISSUE THREAD

**Issue by ParthDesai** [Simversity/gottp#3]
Even if we raise http error with different error code, http response has always error code 200

**Comment by meson10** [comment]
Can you submit a sample ?

**Comment by ParthDesai** [comment]
https://github.com/ParthDesai/sc-notifications

**Comment by ParthDesai** [comment]
I am talking about status code of http request, Not json element "status".

**Comment by meson10** [comment]
Ah Ok. Yeah that is ALWAYS 200 at the moment, because its returned as a json document.
Good point. We should aim at changing that to HTTPRequestStatus itself. :+1:

**Comment by meson10** [comment]
This is Intentional. Since PIPE requests cannot break the entire response, they return the status code as a JSON field instead. This is to keep the response consistent whether or not the request is sent directly or via Pipe.
